apiVersion: v1
kind: Service
metadata:
  name: sftp
spec:
  ports:
    - name: 2222-tcp
      nodePort: 32700
      port: 2222
      protocol: TCP
      targetPort: 2222
  selector:
    service: sftp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

